### ISSUE TITLE
cucumber: 0 tests passed shown in console log

### ISSUE THREAD

**Issue by shrop** [meteor-velocity/console-reporter#3]
I am getting `cucumber: 0 tests passed` in the console right under where console shows that some scenarios passed. I may not be understanding what that is all about, but was curious if you know. :) Thanks much!

See screenshot:

<img src="https://www.evernote.com/shard/s1/sh/c9590863-332a-49bb-a771-fa132ef8ae56/e390b01df00edff8c8b7f2c0a708c2af/deep/0/console-reporter.png" alt="console%20reporter" />

**Comment by samhatoum** [comment]
hmm, do you have the console reporter installed? Might have somehow made it to the mirror?

**Comment by samhatoum** [comment]
sorry, I assumed this was the cucumber repo!

**Comment by shrop** [comment]
no problem @samhatoum. Yep, console reporter installed. I think `ucumber: 0 tests passed` is coming from console reporter.

**Comment by SamHatoum** [comment]
and now I've made you look like you're talking to yourself! :) sorry

**Comment by SamHatoum** [comment]
it's the console reporter for sure. Have you tried cucumber 0.6.0? That looks like the older cuke reports

**Comment by shrop** [comment]
:)

Ok, here is what I am running: xolvio:cucumber                0.5.5\* CucumberJS for Velocity
Is older.. let me give that a go and check back in. Thanks!

**Comment by SamHatoum** [comment]
Be sure to read the breaking changes in 0.6.1

**Comment by shrop** [comment]
Yeah, we were quite a bit behind on velocity related things.

Still getting `cucumber: 0 tests passed`, but other aspects of the console reporter are improved!

**Comment by ghost** [comment]
Fixed in xolvio:cucumber@0.6.3

**Comment by shrop** [comment]
@Sanjo and @samhatoum, thanks for the help. I can confirm that xolvio:cucumber@0.6.3 fixes this. I also had to make changes per your breaking changes docs to existing cucumber tests :)

Thanks!
