### ISSUE TITLE
Crashes without velocity

### ISSUE THREAD

**Issue by lorensr** [meteor-velocity/console-reporter#4]
`ReferenceError: VelocityAggregateReports is not defined`

Either `package.js` should depend on velocity, or pkg should not assume velocity is installed.

**Comment by sungwoncho** [comment]
I think this package should depend on `velocity:core` just as `html-reporter` [does](https://github.com/meteor-velocity/html-reporter/blob/devel/package.js#L11).

**Comment by ghost** [comment]
> I think this package should depend on velocity:core just as html-reporter does.

Yes.
